import { PropsWithChildren } from "react";

import type { Metadata } from "next";

import AuthSessionProvider from "@/components/providers/AuthSessionProvider";
import { auth } from "@/utils/auth";

import { pretendard } from "./fonts";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<PropsWithChildren>) {
  const session = await auth();

  return (
    <html lang="ko">
      <body className={`${pretendard.variable} antialiased`}>
        <AuthSessionProvider session={session}>
          <main className="max-w-[500px] w-full">{children}</main>
        </AuthSessionProvider>
      </body>
    </html>
  );
}
