import { PropsWithChildren } from "react";

import type { Metadata } from "next";
import Image from "next/image";

import AuthSessionProvider from "@/components/providers/AuthSessionProvider";
import { auth } from "@/utils/auth";
import { cn } from "@/utils/cn";

import { pretendard } from "./fonts";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RightSideImage = () => (
  <div className="w-full relative z-0">
    <div className={cn("absolute left-[-180px] top-[45%] translate-y-[-45%]")}>
      <div className={cn("relative", "w-[370px] h-[370px]")}>
        <Image
          src="/images/background/1.png"
          alt="left-image"
          fill
          objectFit="contain"
        />
      </div>
    </div>

    <div className={cn("absolute", "top-[-25px]", "left-[62px]")}>
      <div className={cn("relative", "w-[336px] h-[333px]")}>
        <Image
          src="/images/background/2.png"
          alt="top-image"
          fill
          objectFit="contain"
        />
      </div>
    </div>

    <div
      className={cn(
        "absolute",
        "top-[65%] translate-y-[-65%]",
        "right-[-100px]"
      )}
    >
      <div className={cn("relative", "w-[300px] h-[300px]")}>
        <Image
          src="/images/background/3.png"
          alt="right-image"
          fill
          objectFit="contain"
        />
      </div>
    </div>

    <div className={cn("absolute", "bottom-[-25px]", "right-[100px]")}>
      <div className={cn("relative", "w-[300px] h-[300px]")}>
        <Image
          src="/images/background/4.png"
          alt="bottom-image"
          fill
          objectFit="contain"
        />
      </div>
    </div>

    {/* text */}
    <div className="absolute left-[50%] translate-x-[-50%] top-[50%] translate-y-[-50%] flex flex-col items-center gap-[20px]">
      {/* icon - 성훈님이 아이콘 만드신거 적용하면 될 듯 합니다. */}

      <div className="flex flex-col">
        <p className="text-[32px] text-[#FFFFFF] font-medium">
          오늘 나의 추억은,
        </p>
        <p className="text-[32px] text-[#FFFFFF] font-black">
          어디서 남겨볼까?
        </p>
      </div>
    </div>
  </div>
);

export default async function RootLayout({
  children,
}: Readonly<PropsWithChildren>) {
  const session = await auth();

  return (
    <html lang="ko">
      <body className={`${pretendard.variable} antialiased`}>
        <AuthSessionProvider session={session}>
          <main className="min-h-screen">
            {/* pc */}
            <div
              className={cn(
                "pc-s:flex hidden w-full overflow-hidden",
                "bg-gradient-to-br from-[#E0D7FB] to-[#6436EA]",
                "pc-l:pl-[130px]"
              )}
            >
              <div
                className={cn(
                  "max-w-[472px] w-full",
                  "z-[100]",
                  // TODO 맵 등록되면 지우자
                  "bg-white"
                )}
              >
                {children}
              </div>

              <RightSideImage />
            </div>

            {/* mobile */}
            <div className="pc-s:hidden w-full">{children}</div>
          </main>
        </AuthSessionProvider>
      </body>
    </html>
  );
}
